"""
LUMEN — Production Launch Readiness v1.0 — Canonical Checklist Seed
===================================================================

The single source of truth for the ~130-item go-live checklist a team walks
through **before accepting the first real investor money**. This is the artifact
that catches the last 1–2% of problems that are invisible to any single contract
or harness.

Design notes
------------
* Each item has a stable ``id`` (snake_case), a ``domain``, a ``severity`` and an
  ``owner`` role. Items that can be proven by the running system carry an
  ``auto`` detector key (see ``launch_checklist_engine._DETECTORS``); the rest are
  ``manual`` (owner / legal / ops blocked) and require an explicit admin override
  with evidence before they can go green.
* SEVERITY  : blocker | critical | major | minor
  ``blocker`` items MUST be green (auto or overridden) before go-live.
* OWNER     : owner | ops | eng | legal | compliance
* The canonical Markdown document ``/app/docs/PRODUCTION_LAUNCH_READINESS_v1.0.md``
  is generated from THIS seed — never edit the doc by hand.

Bilingual: every item carries Ukrainian (primary) + English labels.
"""
from __future__ import annotations

LAUNCH_CHECKLIST_VERSION = "1.0"

SEVERITIES = ("blocker", "critical", "major", "minor")
OWNERS = ("owner", "ops", "eng", "legal", "compliance")

DOMAINS: list[dict] = [
    {"id": "funding",             "label_uk": "A2 — Реальні рейки поповнення",        "label_en": "A2 — Real Funding Rails",          "order": 1},
    {"id": "withdrawal",          "label_uk": "A3 — Реальні рейки виводу",            "label_en": "A3 — Real Withdrawal Rails",       "order": 2},
    {"id": "provider_validation", "label_uk": "RV — Валідація провайдерів (Email)",   "label_en": "RV — Real Provider Validation",    "order": 3},
    {"id": "money_cycle",         "label_uk": "Повний грошовий цикл (E2E)",           "label_en": "End-to-End Money Cycle",           "order": 4},
    {"id": "compliance",          "label_uk": "Compliance / AML / KYC / Санкції",     "label_en": "Compliance / AML / KYC / Sanctions","order": 5},
    {"id": "legal",               "label_uk": "Юридичний пакет",                      "label_en": "Legal Package",                    "order": 6},
    {"id": "security",            "label_uk": "Безпека",                              "label_en": "Security",                         "order": 7},
    {"id": "data_integrity",      "label_uk": "Цілісність даних / Інваріанти",        "label_en": "Data Integrity / Invariants",      "order": 8},
    {"id": "operations",          "label_uk": "Операції / SOP / DR",                  "label_en": "Operations / SOP / DR",            "order": 9},
    {"id": "reporting",           "label_uk": "Звітність / Прозорість",               "label_en": "Reporting / Transparency",         "order": 10},
    {"id": "infrastructure",      "label_uk": "Інфраструктура / Деплой",              "label_en": "Infrastructure / Deployment",      "order": 11},
    {"id": "investor_experience", "label_uk": "Досвід інвестора",                     "label_en": "Investor Experience",              "order": 12},
]


def _i(id, domain, sev, owner, auto, uk, en, ev_uk="", ev_en=""):
    return {
        "id": id, "domain": domain, "severity": sev, "owner": owner,
        "auto": auto,  # detector key or None (manual)
        "label_uk": uk, "label_en": en,
        "evidence_uk": ev_uk, "evidence_en": ev_en,
    }


# ───────────────────────────────────────────────────────────────────────────
# THE CHECKLIST (~130 items)
# ───────────────────────────────────────────────────────────────────────────

CHECKLIST_ITEMS: list[dict] = [
    # ── A2 — Real Funding Rails (owner / credential-blocked) ──────────────
    _i("fund_stripe_live", "funding", "blocker", "owner", None,
       "Stripe Live: акаунт активований, ключі в проді, payout-рахунок підключено",
       "Stripe Live: account activated, live keys in prod, payout bank linked",
       "Перевірити Stripe Dashboard → Live mode → Activated", "Stripe Dashboard → Live mode → Activated"),
    _i("fund_kyb_completed", "funding", "blocker", "owner", None,
       "KYB бізнесу пройдено у платіжного провайдера (документи, UBO, ліцензії)",
       "Business KYB completed with payment provider (docs, UBO, licences)"),
    _i("fund_real_iban", "funding", "blocker", "owner", None,
       "Реальний IBAN відкрито на юр-особу платформи/SPV",
       "Real IBAN opened for platform/SPV legal entity"),
    _i("fund_sepa_inbound", "funding", "blocker", "owner", None,
       "SEPA inbound: банк приймає вхідні перекази на funding-рахунок",
       "SEPA inbound: bank accepts incoming transfers to funding account"),
    _i("fund_swift_inbound", "funding", "critical", "owner", None,
       "SWIFT inbound: реквізити для міжнародних інвесторів підтверджені",
       "SWIFT inbound: correspondent details confirmed for intl investors"),
    _i("fund_monobank_acquiring", "funding", "major", "owner", None,
       "Локальний еквайринг підключено (за потреби, з автоконвертацією в USD)",
       "Local acquiring connected (if a local rail is needed, auto-converted to USD)"),
    _i("fund_provider_selected", "funding", "critical", "owner", None,
       "Платіжний провайдер обрано та закріплено в конфігурації (не manual_ops)",
       "Payment provider selected and pinned in config (not manual_ops)"),
    _i("fund_webhook_secured", "funding", "critical", "eng", "funding_webhook_secret",
       "Webhook поповнення підписаний секретом і верифікується",
       "Funding webhook signed with secret and verified server-side"),
    _i("fund_idempotency", "funding", "critical", "eng", "funding_idempotency",
       "Ідемпотентність зарахувань (повтор webhook не дублює ledger)",
       "Funding idempotency (webhook replay does not double-post ledger)"),
    _i("fund_currency_support", "funding", "major", "eng", "fx_live",
       "Підтримка валют USD/USDT/EUR з живим FX на момент зарахування",
       "USD/USDT/EUR support with live FX at credit time"),
    _i("fund_min_max_limits", "funding", "major", "ops", None,
       "Ліміти мінімального/максимального поповнення налаштовані",
       "Min/max funding limits configured"),
    _i("fund_proof_flow", "funding", "minor", "ops", "funding_proof_flow",
       "Потік підтвердження платежу (payment proof) працює для ручних рейок",
       "Payment-proof flow works for manual rails"),

    # ── A3 — Real Withdrawal Rails ────────────────────────────────────────
    _i("wd_channel_live", "withdrawal", "blocker", "owner", None,
       "Хоча б один реальний канал виводу активний (SEPA/SWIFT/банк-API/CSV)",
       "At least one real withdrawal channel live (SEPA/SWIFT/bank-API/CSV)"),
    _i("wd_sepa_payout", "withdrawal", "critical", "owner", None,
       "SEPA payout перевірено реальним переказом",
       "SEPA payout verified with a real transfer"),
    _i("wd_swift_payout", "withdrawal", "major", "owner", None,
       "SWIFT payout реквізити та маршрут підтверджені",
       "SWIFT payout details and routing confirmed"),
    _i("wd_bank_csv_import", "withdrawal", "major", "ops", None,
       "Імпорт банківського CSV у реконсиляцію виводів працює",
       "Bank CSV import into withdrawal reconciliation works"),
    _i("wd_approval_workflow", "withdrawal", "critical", "eng", "withdrawal_approval",
       "Workflow підтвердження виводу (maker/checker) реалізовано",
       "Withdrawal approval workflow (maker/checker) implemented"),
    _i("wd_aml_rescreen", "withdrawal", "critical", "compliance", "sanctions_screening",
       "AML/санкційний ре-скринінг бенефіціара перед виводом",
       "AML/sanctions re-screen of beneficiary before withdrawal"),
    _i("wd_limits_velocity", "withdrawal", "major", "ops", None,
       "Ліміти та velocity-контролі виводу налаштовані",
       "Withdrawal limits and velocity controls configured"),
    _i("wd_bank_fee_model", "withdrawal", "major", "ops", None,
       "Модель банківських комісій врахована у виплаті інвестору",
       "Bank fee model accounted for in investor payout"),
    _i("wd_reconciliation", "withdrawal", "critical", "ops", "reconciliation_clean",
       "Реконсиляція виводів: ledger ↔ банк зводиться без розривів",
       "Withdrawal reconciliation: ledger ↔ bank ties out cleanly"),
    _i("wd_failed_retry", "withdrawal", "minor", "eng", "payout_records_consistent",
       "Обробка невдалих/повернутих виплат (retry/return) реалізована",
       "Failed/returned payout handling (retry/return) implemented"),

    # ── RV — Real Provider Validation (Email) ─────────────────────────────
    _i("rv_gmail_oauth", "provider_validation", "critical", "ops", None,
       "Gmail: реальний OAuth consent у проді пройдено",
       "Gmail: real OAuth consent in production completed"),
    _i("rv_gmail_webhook", "provider_validation", "major", "eng", None,
       "Gmail: push-webhook (Pub/Sub) отримує реальні події",
       "Gmail: push webhook (Pub/Sub) receiving real events"),
    _i("rv_gmail_roundtrip", "provider_validation", "critical", "ops", None,
       "Gmail: реальний лист туди-назад успішно проходить",
       "Gmail: real email round-trip succeeds"),
    _i("rv_gmail_adapter_ready", "provider_validation", "minor", "eng", "gmail_adapter_present",
       "Gmail adapter архітектурно готовий (preflight contract зелений)",
       "Gmail adapter architecturally ready (preflight contract green)"),
    _i("rv_outlook_tenant", "provider_validation", "major", "ops", None,
       "Outlook: реальний tenant + app-реєстрація підтверджені",
       "Outlook: real tenant + app registration confirmed"),
    _i("rv_outlook_webhook", "provider_validation", "major", "eng", None,
       "Outlook: subscription webhook отримує реальні події",
       "Outlook: subscription webhook receiving real events"),
    _i("rv_outlook_roundtrip", "provider_validation", "major", "ops", None,
       "Outlook: реальний лист туди-назад успішно проходить",
       "Outlook: real email round-trip succeeds"),
    _i("rv_outlook_adapter_ready", "provider_validation", "minor", "eng", "outlook_adapter_present",
       "Outlook adapter архітектурно готовий (preflight contract зелений)",
       "Outlook adapter architecturally ready (preflight contract green)"),
    _i("rv_email_deliverability", "provider_validation", "critical", "eng", None,
       "SPF / DKIM / DMARC налаштовано для домену відправника",
       "SPF / DKIM / DMARC configured for sending domain"),
    _i("rv_transactional_email", "provider_validation", "major", "eng", "email_verification_ready",
       "Транзакційна пошта (верифікація/нотифікації) працює в проді",
       "Transactional email (verification/notifications) works in prod"),

    # ── End-to-End Money Cycle ────────────────────────────────────────────
    _i("mc_real_cycle_executed", "money_cycle", "blocker", "owner", None,
       "Реальний цикл виконано: інвестор→поповнення→ledger→частка→сертифікат→дивіденд→вивід→банк",
       "Real cycle executed: investor→funding→ledger→ownership→certificate→dividend→withdrawal→bank"),
    _i("mc_funding_to_ledger", "money_cycle", "critical", "eng", "funding_ledger_link",
       "Поповнення коректно постить запис у ledger",
       "Funding correctly posts a ledger entry"),
    _i("mc_ledger_to_ownership", "money_cycle", "critical", "eng", "ownership_consistent",
       "Ledger → частка власності оновлюється коректно (≤100%)",
       "Ledger → ownership updates correctly (≤100%)"),
    _i("mc_certificate_issue", "money_cycle", "critical", "eng", "first_certificate",
       "Сертифікат власності випускається при підтвердженні частки",
       "Ownership certificate issued on confirmed stake"),
    _i("mc_dividend_calc", "money_cycle", "critical", "eng", "dividend_scheduler",
       "Дивіденд нараховується планувальником (D1) коректно",
       "Dividend accrued by scheduler (D1) correctly"),
    _i("mc_rounding_policy", "money_cycle", "critical", "eng", None,
       "Політика округлення перевірена на реальних сумах (без втрати копійок)",
       "Rounding policy verified on real amounts (no lost cents)"),
    _i("mc_fx_accuracy", "money_cycle", "critical", "eng", "fx_live",
       "FX-конвертація точна на момент проводки (НБУ snapshot)",
       "FX conversion accurate at posting time (NBU snapshot)"),
    _i("mc_bank_fee_recon", "money_cycle", "major", "ops", None,
       "Банківські комісії узгоджені у фактичному циклі",
       "Bank fees reconciled in the actual cycle"),
    _i("mc_tax_postings", "money_cycle", "critical", "eng", "tax_engine_configured",
       "Податкові проводки (ПДФО 18% + ВЗ 1.5%) застосовані до дивіденду",
       "Tax postings (PIT 18% + MT 1.5%) applied to dividend"),
    _i("mc_reconciliation_tie", "money_cycle", "critical", "ops", "reconciliation_clean",
       "Підсумкова реконсиляція циклу зводиться до нуля",
       "End-of-cycle reconciliation ties to zero"),
    _i("mc_operator_manual_steps", "money_cycle", "major", "ops", None,
       "Усі ручні кроки операторів задокументовані та призначені",
       "All operator manual steps documented and assigned"),
    _i("mc_statement_generated", "money_cycle", "minor", "eng", "statements_available",
       "Виписка інвестора за цикл згенерована коректно",
       "Investor statement for the cycle generated correctly"),

    # ── Compliance / AML / KYC / Sanctions ────────────────────────────────
    _i("cmp_sanctions_live", "compliance", "blocker", "compliance", "sanctions_screening",
       "Санкційний/PEP скринінг активний на онбордингу та транзакціях",
       "Sanctions/PEP screening active on onboarding and transactions"),
    _i("cmp_ofac_fresh", "compliance", "critical", "compliance", "ofac_watchlist_fresh",
       "Watchlist оновлюється з OFAC (свіжість ≤ 24–48 год)",
       "Watchlist auto-refreshes from OFAC (freshness ≤ 24–48h)"),
    _i("cmp_kyc_pipeline", "compliance", "blocker", "compliance", "kyc_pipeline",
       "KYC-пайплайн працює: збір→перевірка→рішення→аудит",
       "KYC pipeline works: collect→verify→decide→audit"),
    _i("cmp_kyc_provider", "compliance", "critical", "owner", None,
       "Реальний KYC-провайдер підключено (документи + liveness)",
       "Real KYC provider connected (documents + liveness)"),
    _i("cmp_kyb_investors", "compliance", "major", "compliance", None,
       "KYB для інституційних інвесторів/SPV налаштовано",
       "KYB for institutional investors/SPVs in place"),
    _i("cmp_transaction_monitoring", "compliance", "critical", "compliance", None,
       "Моніторинг транзакцій з порогами та алертами увімкнено",
       "Transaction monitoring with thresholds and alerts enabled"),
    _i("cmp_sar_procedure", "compliance", "major", "compliance", None,
       "Процедура SAR/STR (звіт про підозрілу активність) визначена",
       "SAR/STR (suspicious activity report) procedure defined"),
    _i("cmp_mlro_assigned", "compliance", "critical", "owner", None,
       "Призначено відповідального за AML (MLRO/комплаєнс-офіцер)",
       "AML responsible officer (MLRO) assigned"),
    _i("cmp_risk_scoring", "compliance", "major", "compliance", None,
       "Ризик-скоринг інвесторів (low/medium/high) застосовується",
       "Investor risk scoring (low/medium/high) applied"),
    _i("cmp_accreditation", "compliance", "major", "eng", "accreditation_consistent",
       "Перевірка акредитації/кваліфікації інвестора послідовна",
       "Investor accreditation/qualification checks consistent"),
    _i("cmp_pep_review", "compliance", "major", "compliance", None,
       "PEP-збіги мають workflow ручного перегляду/ескалації",
       "PEP matches have manual review/escalation workflow"),
    _i("cmp_record_retention", "compliance", "minor", "legal", None,
       "Строки зберігання KYC/AML записів відповідають закону",
       "KYC/AML record retention periods comply with law"),

    # ── Legal Package ─────────────────────────────────────────────────────
    _i("legal_tos", "legal", "blocker", "legal", "legal_doc_tos",
       "Terms of Service опубліковано та узгоджено юристом",
       "Terms of Service published and counsel-approved"),
    _i("legal_privacy", "legal", "blocker", "legal", "legal_doc_privacy",
       "Privacy Policy опубліковано (GDPR/локальне законодавство)",
       "Privacy Policy published (GDPR/local law)"),
    _i("legal_aml_policy", "legal", "blocker", "legal", "legal_doc_aml",
       "AML Policy задокументовано та доступно",
       "AML Policy documented and available"),
    _i("legal_kyc_policy", "legal", "critical", "legal", "legal_doc_kyc",
       "KYC Policy задокументовано",
       "KYC Policy documented"),
    _i("legal_risk_disclosure", "legal", "blocker", "legal", "legal_doc_risk",
       "Risk Disclosure (попередження про ризики) опубліковано",
       "Risk Disclosure published"),
    _i("legal_dividend_policy", "legal", "critical", "legal", "legal_doc_dividend",
       "Dividend Policy опубліковано",
       "Dividend Policy published"),
    _i("legal_secondary_rules", "legal", "critical", "legal", "legal_doc_secondary",
       "Secondary Market Rules опубліковано",
       "Secondary Market Rules published"),
    _i("legal_investor_agreement", "legal", "blocker", "legal", None,
       "Інвесторський договір/SPV-документи перевірені юристом",
       "Investor agreement/SPV documents reviewed by counsel"),
    _i("legal_cookie_consent", "legal", "major", "eng", None,
       "Cookie-consent банер відповідає політиці",
       "Cookie consent banner matches policy"),
    _i("legal_gdpr_dsr", "legal", "major", "legal", None,
       "Процеси GDPR (доступ/видалення даних — DSR) визначені",
       "GDPR processes (data access/erasure — DSR) defined"),
    _i("legal_entity_structure", "legal", "critical", "owner", None,
       "Юридична структура (платформа + SPV) оформлена та чинна",
       "Legal structure (platform + SPVs) incorporated and valid"),
    _i("legal_regulatory_stance", "legal", "blocker", "owner", None,
       "Регуляторна позиція/ліцензування підтверджені юристом",
       "Regulatory stance/licensing confirmed by counsel"),

    # ── Security ──────────────────────────────────────────────────────────
    _i("sec_score_threshold", "security", "blocker", "eng", "security_score_ok",
       "Бал безпеки ≥ 90/100 (автоаудит)",
       "Security score ≥ 90/100 (auto-audit)"),
    _i("sec_rate_limit", "security", "critical", "eng", "rate_limit_enabled",
       "Rate limiting увімкнено на чутливих ендпоінтах",
       "Rate limiting enabled on sensitive endpoints"),
    _i("sec_2fa", "security", "critical", "eng", "two_factor_available",
       "2FA доступна для admin/staff акаунтів",
       "2FA available for admin/staff accounts"),
    _i("sec_password_policy", "security", "major", "eng", "password_policy",
       "Політика паролів (складність/lockout) діє",
       "Password policy (complexity/lockout) enforced"),
    _i("sec_headers", "security", "major", "eng", "security_headers",
       "Security-заголовки (CSP/HSTS/тощо) встановлюються",
       "Security headers (CSP/HSTS/etc.) set"),
    _i("sec_upload_validation", "security", "major", "eng", "upload_security",
       "Валідація завантажень (тип/розмір/санітизація) діє",
       "Upload validation (type/size/sanitisation) enforced"),
    _i("sec_audit_log", "security", "critical", "eng", "audit_log_active",
       "Аудит-лог фіксує адмін/фінансові дії",
       "Audit log captures admin/financial actions"),
    _i("sec_secrets_mgmt", "security", "blocker", "eng", None,
       "Секрети у сховищі/env, не в коді; ротація визначена",
       "Secrets in vault/env, not in code; rotation defined"),
    _i("sec_rbac", "security", "critical", "eng", "permissions_clean",
       "RBAC/матриця дозволів без порушень",
       "RBAC/permission matrix with no violations"),
    _i("sec_session_mgmt", "security", "major", "eng", None,
       "Керування сесіями (термін дії/відкликання) налаштовано",
       "Session management (expiry/revocation) configured"),
    _i("sec_pentest", "security", "major", "owner", None,
       "Зовнішній pentest/security review проведено перед запуском",
       "External pentest/security review done before launch"),
    _i("sec_backup_encryption", "security", "major", "eng", None,
       "Резервні копії шифруються та зберігаються безпечно",
       "Backups encrypted and stored securely"),

    # ── Data Integrity / Invariants ───────────────────────────────────────
    _i("di_invariants_pass", "data_integrity", "blocker", "eng", "lr2_invariants_pass",
       "Усі інваріанти LR2 (капітал/власність/виплати) зелені",
       "All LR2 invariants (capital/ownership/payouts) green"),
    _i("di_reporting_integrity", "data_integrity", "critical", "eng", "reporting_integrity_pass",
       "Звітність відповідає джерелу істини (cross-verify)",
       "Reporting matches source of truth (cross-verify)"),
    _i("di_ownership_le_100", "data_integrity", "blocker", "eng", "ownership_consistent",
       "Сумарна власність по активу ≤ 100%",
       "Total ownership per asset ≤ 100%"),
    _i("di_ledger_balanced", "data_integrity", "critical", "eng", "reconciliation_clean",
       "Ledger збалансований (debits=credits)",
       "Ledger balanced (debits=credits)"),
    _i("di_no_demo_in_prod", "data_integrity", "blocker", "eng", "no_demo_in_prod",
       "У проді відсутні демо-дані/демо-акаунти",
       "No demo data/demo accounts in production"),
    _i("di_conflicts_clean", "data_integrity", "major", "compliance", "conflicts_clean",
       "Немає високоризикових конфліктів інтересів (LP=GP, voter=operator)",
       "No high-risk conflicts of interest (LP=GP, voter=operator)"),
    _i("di_distribution_waterfall", "data_integrity", "critical", "eng", "distribution_integrity",
       "Σ ліній розподілу = чистий дохід (waterfall)",
       "Σ distribution lines = net income (waterfall)"),
    _i("di_certificate_backing", "data_integrity", "major", "eng", "cert_asset_backed",
       "Кожен активний сертифікат прив'язаний до активу",
       "Every active certificate is asset-backed"),
    _i("di_unique_compliance", "data_integrity", "major", "eng", "unique_compliance_profile",
       "Унікальність compliance-профілю на інвестора",
       "Unique compliance profile per investor"),
    _i("di_fund_nav", "data_integrity", "major", "eng", "fund_nav_consistent",
       "NAV фонду = сума cert NAV по SPV",
       "Fund NAV = sum of cert NAV across SPVs"),

    # ── Operations / SOP / DR ─────────────────────────────────────────────
    _i("ops_runbooks", "operations", "critical", "ops", "sop_runbooks",
       "Інцидент-ранбуки (funding/withdrawal/recon/sanctions/payout) існують",
       "Incident runbooks (funding/withdrawal/recon/sanctions/payout) exist"),
    _i("ops_dr_verified", "operations", "blocker", "ops", "dr_backup_verified",
       "DR: backup→restore→compare перевірено (ідентичність колекцій)",
       "DR: backup→restore→compare verified (collections identical)"),
    _i("ops_backup_schedule", "operations", "critical", "ops", None,
       "Резервне копіювання заплановано та моніториться",
       "Backups scheduled and monitored"),
    _i("ops_oncall", "operations", "critical", "ops", None,
       "On-call ротація та ескалаційні контакти визначені",
       "On-call rota and escalation contacts defined"),
    _i("ops_monitoring", "operations", "critical", "eng", None,
       "Моніторинг/дашборди (uptime/latency/помилки) налаштовані",
       "Monitoring/dashboards (uptime/latency/errors) configured"),
    _i("ops_error_tracking", "operations", "major", "eng", "error_tracking_active",
       "Трекінг помилок увімкнено та переглядається",
       "Error tracking enabled and reviewed"),
    _i("ops_recon_ownership", "operations", "critical", "ops", None,
       "Призначено відповідального за реконсиляцію та винятки",
       "Owner assigned for reconciliation and exceptions"),
    _i("ops_kyc_escalation", "operations", "major", "compliance", None,
       "Шлях ескалації KYC/AML винятків визначено",
       "KYC/AML exception escalation path defined"),
    _i("ops_sla_defined", "operations", "minor", "ops", "sla_engine",
       "SLA на відповіді/обробку визначені та трекаються",
       "Response/processing SLAs defined and tracked"),
    _i("ops_status_page", "operations", "minor", "ops", None,
       "Сторінка статусу/комунікація інцидентів інвесторам готова",
       "Status page/investor incident comms ready"),
    _i("ops_change_management", "operations", "minor", "eng", None,
       "Процес деплою/відкату (change management) задокументовано",
       "Deploy/rollback (change management) process documented"),
    _i("ops_data_export", "operations", "minor", "ops", "payout_export",
       "Експорт виплат/даних для банку/бухгалтерії працює",
       "Payout/data export for bank/accounting works"),

    # ── Reporting / Transparency ──────────────────────────────────────────
    _i("rep_quarterly", "reporting", "critical", "eng", "quarterly_reports",
       "Квартальні звіти генеруються та доступні інвесторам",
       "Quarterly reports generated and available to investors"),
    _i("rep_factsheets", "reporting", "major", "eng", "factsheets_available",
       "Фактшити фондів/активів формуються",
       "Fund/asset factsheets produced"),
    _i("rep_statements", "reporting", "critical", "eng", "statements_available",
       "Виписки інвестора (внески/дивіденди/податки) коректні",
       "Investor statements (contributions/dividends/taxes) correct"),
    _i("rep_certificates", "reporting", "critical", "eng", "first_certificate",
       "Сертифікати власності доступні для завантаження",
       "Ownership certificates downloadable"),
    _i("rep_dividend_history", "reporting", "major", "eng", "payout_history",
       "Історія дивідендів/виплат прозоро відображається",
       "Dividend/payout history transparently displayed"),
    _i("rep_portfolio_transparency", "reporting", "major", "eng", None,
       "Портфель інвестора показує частку, NAV, дохідність прозоро",
       "Investor portfolio shows stake, NAV, yield transparently"),
    _i("rep_tax_documents", "reporting", "major", "eng", "tax_engine_configured",
       "Податкові документи/довідки за рік формуються",
       "Annual tax documents/certificates produced"),
    _i("rep_audit_trail", "reporting", "major", "eng", "audit_log_active",
       "Повний аудит-слід фінансових подій доступний адміну",
       "Full audit trail of financial events available to admin"),
    _i("rep_fee_transparency", "reporting", "minor", "ops", None,
       "Комісії платформи прозоро розкриті інвестору",
       "Platform fees transparently disclosed to investor"),
    _i("rep_regulatory_reporting", "reporting", "major", "legal", None,
       "Регуляторна/податкова звітність (якщо вимагається) налаштована",
       "Regulatory/tax reporting (if required) set up"),

    # ── Infrastructure / Deployment ───────────────────────────────────────
    _i("inf_prod_env_gate", "infrastructure", "blocker", "eng", "prod_env_gate",
       "LUMEN_ENV=production вмикає прод-гейти (seed off, bypass off, purge demo)",
       "LUMEN_ENV=production enables prod gates (seed off, bypass off, purge demo)"),
    _i("inf_demo_purge", "infrastructure", "blocker", "eng", "no_demo_in_prod",
       "Демо-акаунти/quick-access bypass вимкнено у проді",
       "Demo accounts/quick-access bypass disabled in prod"),
    _i("inf_env_vars", "infrastructure", "critical", "eng", None,
       "Усі прод env-змінні/секрети задані та перевірені",
       "All prod env vars/secrets set and verified"),
    _i("inf_health_checks", "infrastructure", "major", "eng", None,
       "Health-check ендпоінти налаштовані для оркестратора",
       "Health-check endpoints configured for orchestrator"),
    _i("inf_db_indexes", "infrastructure", "major", "eng", "db_indexes_ensured",
       "Індекси БД створені для ключових колекцій",
       "DB indexes ensured for key collections"),
    _i("inf_scaling", "infrastructure", "minor", "eng", None,
       "Параметри масштабування/ресурсів визначені під навантаження",
       "Scaling/resource parameters set for expected load"),
    _i("inf_tls", "infrastructure", "critical", "eng", None,
       "TLS/HTTPS примусово на всіх доменах",
       "TLS/HTTPS enforced on all domains"),
    _i("inf_cors", "infrastructure", "major", "eng", None,
       "CORS обмежено до довірених origin у проді",
       "CORS restricted to trusted origins in prod"),
    _i("inf_log_retention", "infrastructure", "minor", "ops", None,
       "Зберігання/ротація логів налаштовані",
       "Log retention/rotation configured"),
    _i("inf_domain_dns", "infrastructure", "major", "owner", None,
       "Прод-домен, DNS та сертифікати налаштовані",
       "Prod domain, DNS and certificates configured"),

    # ── Investor Experience ───────────────────────────────────────────────
    _i("ix_onboarding", "investor_experience", "critical", "eng", "first_real_investor",
       "Онбординг інвестора (реєстрація→KYC→перший внесок) безшовний",
       "Investor onboarding (signup→KYC→first contribution) seamless"),
    _i("ix_kyc_flow", "investor_experience", "critical", "eng", "first_kyc_approved",
       "KYC-флоу зрозумілий, зі статусами та підказками",
       "KYC flow clear, with statuses and guidance"),
    _i("ix_funding_ux", "investor_experience", "critical", "eng", "first_funding",
       "UX поповнення зрозумілий, з підтвердженням та квитанцією",
       "Funding UX clear, with confirmation and receipt"),
    _i("ix_portfolio_view", "investor_experience", "major", "eng", None,
       "Кабінет інвестора показує портфель/виплати/документи",
       "Investor cabinet shows portfolio/payouts/documents"),
    _i("ix_notifications", "investor_experience", "major", "eng", "notifications_active",
       "Нотифікації (поповнення/дивіденд/KYC) працюють і локалізовані",
       "Notifications (funding/dividend/KYC) work and are localised"),
    _i("ix_support_channel", "investor_experience", "major", "ops", None,
       "Канал підтримки інвестора визначено та укомплектовано",
       "Investor support channel defined and staffed"),
    _i("ix_localization", "investor_experience", "minor", "eng", "i18n_ready",
       "Локалізація (UA/EN) повна на ключових екранах",
       "Localisation (UA/EN) complete on key screens"),
    _i("ix_mobile_ready", "investor_experience", "minor", "eng", None,
       "Мобільний/адаптивний досвід перевірено",
       "Mobile/responsive experience verified"),
]


def items_by_domain() -> dict[str, list[dict]]:
    out: dict[str, list[dict]] = {d["id"]: [] for d in DOMAINS}
    for it in CHECKLIST_ITEMS:
        out.setdefault(it["domain"], []).append(it)
    return out


def item_index() -> dict[str, dict]:
    return {it["id"]: it for it in CHECKLIST_ITEMS}


# Integrity guards (also asserted by the contract harness)
assert len({it["id"] for it in CHECKLIST_ITEMS}) == len(CHECKLIST_ITEMS), "duplicate item id"
assert all(it["severity"] in SEVERITIES for it in CHECKLIST_ITEMS), "bad severity"
assert all(it["owner"] in OWNERS for it in CHECKLIST_ITEMS), "bad owner"
assert all(it["domain"] in {d["id"] for d in DOMAINS} for it in CHECKLIST_ITEMS), "bad domain"

__all__ = [
    "LAUNCH_CHECKLIST_VERSION", "SEVERITIES", "OWNERS", "DOMAINS",
    "CHECKLIST_ITEMS", "items_by_domain", "item_index",
]
